name: 575_capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - python-dotenv
  - faiss-cpu
  - pip
  - duckdb
  - faiss
  - sentence_transformers
  
  - pip:
      - rank_bm25
      - sentence-transformers
      - langchain
      - langchain-community
      - streamlit
      - datasets
      - ollama